{% set version = "20140914" %}
{% set name = "m4ri" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://bitbucket.org/malb/m4ri/downloads/{{ name }}-{{ version }}.tar.gz
  sha256: 4bc3f53a5116e1ff0720c08f34ce415c88e2fb503437abfd15e196792ec6d5aa
  patches:
    - dll.patch
    - unistd.diff

build:
  number: 1004
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage("m4ri") }}

requirements:
  build:
    - libtool                   # [unix]
    - automake                  # [unix]
    - autoconf                  # [unix]
    - make                      # [unix]
    - m4                        # [unix]
    - {{ compiler('c') }}
    - posix                     # [win]
    - clangdev                  # [win]
    - lld                       # [win]
    - llvmdev                   # [win]
    - m2-automake-wrapper       # [win]
    - m2-libtool                # [win]
    - m2-autoconf               # [win]
    - m2-make                   # [win]
    - m2-m4                     # [win]

  host:
    - libpng
    - zlib

  run:
    - libpng
    - zlib

test:
  commands:
    - test -f ${PREFIX}/include/m4ri/m4ri.h                                   # [unix]
    - test -f ${PREFIX}/lib/lib{{ name }}.a                                   # [unix]
    - test -f ${PREFIX}/lib/lib{{ name }}${SHLIB_EXT}                         # [unix]
    - if not exist %LIBRARY_BIN%\\{{ name }}-0-0-{{ version }}.dll exit 1     # [win]
    - if not exist %LIBRARY_LIB%\\{{ name }}.lib exit 1                       # [win]
    - if not exist %LIBRARY_LIB%\\{{ name }}_static.lib exit 1                # [win]
    - if not exist %LIBRARY_INC%\\{{ name }}\\m4ri.h exit 1                   # [win]

about:
  home: https://bitbucket.org/malb/m4ri
  license: GPLv2+
  license_family: GPL
  license_file: COPYING
  summary: M4RI is a library for fast arithmetic with dense matrices over F2
  dev_url: https://bitbucket.org/malb/m4ri
  doc_url: https://malb.bitbucket.io/m4ri

extra:
  recipe-maintainers:
    - isuruf
    - marcelotrevisani
