{% set version = "20200125" %}
{% set name = "m4ri" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/malb/{{ name }}/archive/refs/tags/release-{{ version }}.tar.gz
  sha256: 7369adcecb72d4dacfb23fd437a6b59a956f76b26dee07f32558cb915a9d6e9d

build:
  skip: true  # [win and vc<14]
  # We temporarily disable the Windows build until we figure out how to build this with autotools_clang_conda again, see https://github.com/conda-forge/m4ri-feedstock/pull/13
  skip: true  # [win]
  number: 0
  run_exports:
    - {{ pin_subpackage("m4ri") }}

requirements:
  build:
    - libtool                # [unix]
    - automake               # [unix]
    - autoconf               # [unix]
    - make                   # [unix]
    - m4                     # [unix]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - autotools_clang_conda  # [win]
  host:
    - libpng
    - zlib

test:
  commands:
    - test -f ${PREFIX}/include/m4ri/m4ri.h                                   # [unix]
    - test -f ${PREFIX}/lib/lib{{ name }}.a                                   # [unix]
    - test -f ${PREFIX}/lib/lib{{ name }}${SHLIB_EXT}                         # [unix]
    - if not exist %LIBRARY_BIN%\\{{ name }}-0-0-{{ version }}.dll exit 1     # [win]
    - if not exist %LIBRARY_LIB%\\{{ name }}.lib exit 1                       # [win]
    - if not exist %LIBRARY_LIB%\\{{ name }}_static.lib exit 1                # [win]
    - if not exist %LIBRARY_INC%\\{{ name }}\\m4ri.h exit 1                   # [win]

about:
  home: https://github.com/malb/m4ri
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: M4RI is a library for fast arithmetic with dense matrices over F2
  dev_url: https://github.com/malb/m4ri

extra:
  recipe-maintainers:
    - isuruf
    - marcelotrevisani
    - saraedum
