{% set version = "20140914" %}
{% set name = "m4ri" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://bitbucket.org/malb/m4ri/downloads/{{ name }}-{{ version }}.tar.gz
  sha256: 4bc3f53a5116e1ff0720c08f34ce415c88e2fb503437abfd15e196792ec6d5aa

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
    - autoconf

  host:
    - libpng
    - zlib

  run:
    - libpng
    - zlib

test:
  commands:
    - test -f ${PREFIX}/include/m4ri/m4ri.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}${SHLIB_EXT}

about:
  home: https://bitbucket.org/malb/m4ri
  license: GPLv2+
  license_family: GPL
  license_file: COPYING
  summary: M4RI is a library for fast arithmetic with dense matrices over F2
  dev_url: https://bitbucket.org/malb/m4ri
  doc_url: https://malb.bitbucket.io/m4ri

extra:
  recipe-maintainers:
    - isuruf
    - marcelotrevisani
