appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: appveyor}
travis:
  secure: {BINSTAR_TOKEN: WhhVlKBLlS1ou/W2kkoUieaajvBUqKTOcVTKciAL7QP9I/jOHQQ7cgxqvALyCMVrzgYxiQXjAhegE+D7Qf+F5TGgaxuScO/NXFQgOCP6B/z4tNfhUQyRE1A8kSfT0IBOvdcUKyVe1K9XZoTLAH08fd1dyRSghf/WU2wJC0NoKr0TNSTsFZ8xIi9Iy42zmzWVqlM09fghOEQ8gS5fGlPgLcy1ow70UuLOrO3lqlSLGXeRdpG4OiGwOx/oIdEt8U+W9MNlv1Z7J5q+lYku7Yc0gvOpuA60iIi8PKyAvbgz7WVSZAuA83MjIhAsQaUIdveoOWQqshlTF7iFQBhkTBzGfuWf+Ha3hx1TDBudjXNUoeV74ZB4Mkktn/PEouzs9wm6hMvuMVtoAOIuu0tGzzD6mFrKfgaQZpWtz93UEEPdJrGGEfM+Pug+epqZWbLOg5VaFDwre8X/R7/NmLtMZ2ORVfsOIf/OU/f2pEeRMZXzOWNYX6uTVEvoNKtsk5B50XXIY/D5tneTYanPNfuVW6qKEja4/NSifc7d/e62AaSO4Pf+GAzihtv5BizMDqMn8f5WHoqWlJ3GKyO9lIqm+Um6YSDqfgjEDudG0/6yQR+OXLeJ+kieXTn/+9vN3Lw1UYKt09Cc62TP8hd5HtuRtQP57OaUR8e8olIkHH9ZjwCJcGM=}
